## List in Python

* A list is a collection of items which internally uses array data structure
* List is dynamically sized array.It allows dynamically insert and delete items,It preallocates extra memory where insertions can happen faster
* They are other ways to store the collection of items .list not only the container(tuples,set,dictionaries)
* when we have different types operations,use different types of containers accordingly
* In array everything is stored in contigious location
* In ptyhon every variable or every member of list is actually reference
* Array stores references this items l[10,20,"GFG",40,True] and these items are stored in different locations
* These refereces must be stored in contiguous location because the underlying datastructure is array.but,the actual items might not be in a contigious locations

#### Internal working of list
- There is underlying data structure, which is contiguous block of memory which stores the references of items.when our list becomes full.The underlying block of memory is replaced with a larger block
- Assumption: initially space for 10 items is allocated
- First 10 items go easily. when we insert 11th item .In that case,the old block of memory will be deallocated and a new block of memory will be allocated of double the size,then n be inserted

#### Digression on Equality
- Consider the fallowing assignments   
list1 = [1,3,5,7]   
list2 = [1,3,5,7]  
list3 = list2  
* All three are equal but there is a difference
1) list1 and list2 are two different lists with same values
2) list2 and list3 are two names for the same list

In [3]:
list1 = [1, 3, 5, 7]
list2 = [1, 3, 5, 7]
list3 = list2

print(list1 == list2)  
print(list2 == list3)  
print(list1 is list2)  
print(list2 is list3)  


True
True
False
True


- x == y check if x and y have same value
- x is y checks if x and y refers to the same object

#### Concatenation
- Like strings,lists can be glued together   
- Note : "+" produces a new list  
list1 = [1,3,5,7]     
list1 = list2   
list1 = list1 +[9]   
- list 1 and list 2 no longer point to the same object


#### Advantages
* Random Access
1. we can get ith element of list in constant time
2. random access is not available in all containers ex: set, dictionaries
* Cache Friendly
1. There is concept called locality of reference .what a cpu does when they fetch an item they store the data in cache memory
2. They also prefetch the nearby locations data, using locality of reference concept
3. In case of lists or arrays ,these items are stored in contiguous locations, when we are traversing throuh a list there are very likely possible these references are already there in the cache
4. cache messes are very less when we have contiguous location items

#### Disadvantages
- Insertion and deletion are slow
- search is also slow for unsorted array

#### Complexities
- Time complexity of list,append operation is constant it's only appending at the end.simillarly,removing the last item which is pop operation is also constant time.
- if we try to insert or remove the item at the middle that's going to take the linear time in the worst case
- Overcoming by set {Insert,Delete,Search} operations

#### List item access

In [1]:
l = [10, 20, 30, 40, 50]
print(l)
print(l[3])
print(l[1])
print(l[-1])
print(l[-2])

[10, 20, 30, 40, 50]
40
20
50
40


#### Insert and search 

In [2]:
l = [10, 20, 30, 40, 50]
l.append(30)
print(l)
l.insert(1, 15)
print(l)
print(15 in l)
print(l.count(30))
print(l.index(30))


[10, 20, 30, 40, 50, 30]
[10, 15, 20, 30, 40, 50, 30]
True
2
3


#### Removal of items

In [2]:
l = [10, 20, 30, 40, 50, 60, 70, 80]
l.remove(20) # .remove  only  remove the value.
print(l)
print(l.pop()) # .pop return the removal item as output
print(l)
print(l.pop(2))
print(l)
del l[1]
print(l)
del l[0:2]
print(l)

[10, 30, 40, 50, 60, 70, 80]
80
[10, 30, 40, 50, 60, 70]
40
[10, 30, 50, 60, 70]
[10, 50, 60, 70]
[60, 70]


#### Some general-purpose

In [4]:
l=[10,40,20,50]
print(max(l))
print(min(l))
print(sum(l))
l.reverse()
print(l)
l.sort()
print(l)


50
10
120
[50, 20, 40, 10]
[10, 20, 40, 50]


In [2]:
# input the list as string
string = input("Enter elements (Space-Separated): ")

# split the strings and store it to a list
lst = string.split()  
print('The list is:', lst)   # printing the list

Enter elements (Space-Separated): GEEKS FOR GEEKS
The list is: ['GEEKS', 'FOR', 'GEEKS']


In [2]:
 ## extend(), this method is used to add multiple elements at the same time at the end of the list.
# Creating a List
List = [1, 2, 3, 4]
print("Initial List: ")
print(List)

List.extend([8, 'Geeks', 'Always'])
print("\nList after performing Extend Operation: ")
print(List)

Initial List: 
[1, 2, 3, 4]

List after performing Extend Operation: 
[1, 2, 3, 4, 8, 'Geeks', 'Always']


### Average or mean of a list

In [2]:
def average(l):
    sum = 0
    for x in l:
        sum = sum + x
    n = len(l)
    return sum/n

l = [10, 40, 20, 50]
print(average(l))
        

30.0


In [4]:
def average(l):
    return sum(l)/len(l)

l = [10, 40,50]
print(average(l))

33.333333333333336


### Separate Even or Odd

In [8]:
def separation(l):
    even = []
    odd = []
    
    for x in l:
        if x % 2 == 0 :
            even.append(x)
        else :
            odd.append(x)            
    return even, odd  ## Afunction can return multiple values(it mainly becomes a tuple) and we get return value also a tuple


l = [10, 40,50,33,43,76,31]
even,odd = separation(l)  ## And we unpack a tuples and we can get a two values again . and These two values here are two lists
print("Even numbers:", even)
print("Odd numbers:", odd)

Even numbers: [10, 40, 50, 76]
Odd numbers: [33, 43, 31]


### Get Smaller Elements

In [3]:
def small(l,n):
    small = []
    for x in l:
        if x<n:
            small.append(x)
    return small
    
l = [10, 40,50,33,43,76,31]
n=50
print(small(l,n))

[10, 40, 33, 43, 31]


### List Comprehension

In [2]:
l = [10, 40,50,33,43,76,31]
l1 = [x for x in l if x % 2 == 0]
print(l1)

[10, 40, 50, 76]


In [4]:
def getsmaller(l,x):
    return[e for e in l if e < x]

l = [10, 40,50,33,43,76,31]
x=50
print(getsmaller(l,x))

[10, 40, 33, 43, 31]


In [7]:
def evenodd(l): 
    even = [x for x in l if x % 2 == 0]
    odd = [x for x in l if x % 2 != 0]
    return even,odd
    

l = [10, 40,50,33,43,76,31]
even,odd = evenodd(l)  ## And we unpack a tuples and we can get a two values again . and These two values here are two lists
print("Even numbers:", even)
print("Odd numbers:", odd)

Even numbers: [10, 40, 50, 76]
Odd numbers: [33, 43, 31]


### Custom max val

In [8]:
def max_find(l):
    temp = l.copy()
    for x in l:
        for e in temp[:]:
            if x > e:
                temp.remove(e)
    return temp

l = [10, 40, 50, 33, 43, 76, 31]
print(max_find(l))


[76]


In [9]:
def max_find(l):
    max_value = l[0]
    for x in l:
        if x > max_value:
            max_value = x
    return max_value

l = [10, 40, 50, 33, 43, 76, 31]
print(max_find(l))


76


In [14]:
### Simple Method

def get_max(l):
    for x in l:
        for y in l:
            if y > x:
                break
        else:
            return x
             
    return none

l = [10, 40, 50, 33, 43, 76, 31]
print(get_max(l))

### Time Complexity o(n^2)

76


The condition if y > x: checks if there is any element y in the list that is greater than the current element x.  
If such an element y is found, the loop breaks, meaning x is not the maximum value.

In [16]:
### Efficient solution

def get_max(l):
    if not l:
        return None
    else:
        res = l[0]
        for i in range(1,len(l)):
            if l[i]>res:
                res = l[i]
        return res
    
l = [10, 40, 50, 33, 43, 76, 31]
print(get_max(l))

### Time Complexity o(n)
### if not l: checks whether the list l is empty.

76


### Second Largest Element in the list

#### Two Traversals

In [2]:
def getMax(l):
    res = l[0]
    for i in range (1,len(l)):
        if l[i] > res:
            res = l[i]
    return res

def getSecMax(l):
    if len(l) <= 1:    ## Case 1 : If there is one element or empty list 
        return None
    lar = getMax(l)
    slar = None
    for x in l:
        if x != lar:
            if slar == None :    ## Case 2 : if there were only one element in list pointing x other than largest then it be slar
                slar = x
            else :
                slar = max(slar,x)
    return slar
            

l = [10, 40, 50, 33, 43, 76, 31]
print(getSecMax(l))

## Time Complexity theta(n)

50


#### One Traversal [Efficient solution]

In [2]:
def getSecMax(l):
    if len(l) <= 1:
        return None
    lar = l[0]
    slar = None
    for x in l[1:]:
        if x > lar:
            slar = lar  #Here we are slar is updating firt. reason is first if we upadate lar then the lar value be discarded
            lar = x
        elif x != lar:
            if slar == None or slar < x :
                slar = x
    return slar

l = [10, 40, 50, 33, 43, 76, 31]
print(getSecMax(l))

50


### Check If list is Sorted or Not

In [2]:
def Check_Sort(l):
    if len(l) <= 1:
        return True
    for i in range(len(l) - 1):
        if l[i] > l[i + 1]:
            return False
    return True

l = [10, 40, 50, 33, 43, 76, 31]
res = Check_Sort(l)
print(res)


False


#### Why len(l) - 1 is needed in check_sort?
- The comparison l[i] > l[i+1] involves accessing the next element (l[i+1]).
- If the loop ran up to len(l), the final iteration would attempt to access l[len(l)], which is out of bounds.
- To prevent this, the loop stops at len(l) - 1 to ensure i+1 is always within range.

In [3]:
def isSorted(l):
    i = 1
    while i < len(l):
        if l[i] < l[i-1]:
            return False
        i += 1
    return True

l = [10, 40, 50, 33, 43, 76, 31]
if isSorted(l):
    print("Yes")
else :
    print("No")

No


In [4]:
def isSorted(l):
    sl = sorted(l)
    if sl == l:
        return True
    else:
        return False
    
l = [10, 40, 50, 33, 43, 76, 31]
if isSorted(l):
    print("Yes")
else :
    print("No")

No


#### Here Difference Between sort and sorted  
- sort : It modifies the given list in sorted order
- sorted : it creates the new list by sorting the given list  
##### In the Same way:  
- reverse : It modifies the given list in reverse order
- reversed : it creates the new list by reversing the given list

### Reverese a List in python

In [3]:
def reverse_list(l):
    print(l[::-1])
    
l = [10, 40, 50, 33, 43, 76, 31]
reverse_list(l)    

#Thus, the overall time complexity of the reverse_list(l) function is:O(n)
#Where n is the length of the list l.

[31, 76, 43, 33, 50, 40, 10]


In [14]:
def reverse(l):
    rev = []
    for i in range(len(l) - 1, -1, -1):
        rev.append(l[i])
    return rev

l = [10,20,30,40]
print(reverse(l))

[40, 30, 20, 10]


- we are appending into the new initialized list so we required to write return statement for output

In [17]:
def reverselist(l):
    s = 0
    e = len(l)-1
    while s < e:
        l[s],l[e] = l[e],l[s]
        s += 1
        e -= 1

l = [10, 20, 30, 40]
reverselist(l)
print(l)  # Print the reversed list after modification

# return l  # Return the reversed list
# print(reverselist(l))  # This will print the reversed list directly

[40, 30, 20, 10]


- we are modifying the list inplace so we choose the choice to not writing return statement. and after functioncall modification takes place then we can print the same list..

### Remove Duplicates from a Sorted array

In [3]:
def remdup(l):
    res = 1
    for i in range (1,len(l)):
            if(l[res-1] != l[i]):
                l[res] = l[i]
                res += 1
    return res


l = [10,20,20,30,30,30,30]
result = remdup(l)
print(l[:result]) # Output the list up to the new length

[10, 20, 30]


##### Initial state:   
l = [10, 20, 20, 30, 30, 30, 30]   
res = 1
  
##### Iterations:   
 
i = 1: l[res-1] = l[0] = 10, l[i] = l[1] = 20  
10 != 20 → Place 20 at l[1], increment res to 2.  

i = 2: l[res-1] = l[1] = 20, l[i] = l[2] = 20  
20 == 20 → No action, continue.  

i = 3: l[res-1] = l[1] = 20, l[i] = l[3] = 30  
20 != 30 → Place 30 at l[2], increment res to 3.  

i = 4, 5, 6: All comparisons result in no action since l[i] = 30.  

##### Final state:  
l = [10, 20, 30, 30, 30, 30, 30] (only the first 3 elements are relevant).  
res = 3  


In [1]:
def remdup(l):
    return list(dict.fromkeys(l))

l = [10, 20, 20, 30, 30, 30, 30]
print(remdup(l))


## Time Complexity O(n): inserting `n` keys into a dict
## Space Complexity O(n): dictionary + result list

[10, 20, 30]


`dict.fromkeys()` removes duplicates while preserving the **first occurrence order** (since Python 3.7+ dictionaries maintain insertion order).

In [3]:
def remdup(l):
    res = []
    for i in l:
        if not res or res[-1] != i:
            res.append(i)
    return res

l = [10, 20, 20, 30, 30, 30, 30]
print(remdup(l))

## Time Complexity: O(n) single traversal
## Space Complexity: O(n) new list created for results

[10, 20, 30]


- `not res` → means **if `res` is empty**, add the first element.

- `res[-1]` → means **the last element** in the `res` list.

- `res[-1] != i` → means **if the last added element is not the same** as the current one, it’s a new (non-duplicate) value.

### Left Rotate a list by One

In [30]:
## Using Direct Methods

### Method 1 Using List Slicing
l = [10,20,30,40]
l = l[1:]+l[0:1]
print(l)

### Method 2 Using Pop , Append Method
l = [10,20,30,40]
l.append(l.pop(0))
print(l)

[20, 30, 40, 10]
[20, 30, 40, 10]


In [32]:
def rotateByOne(l):
    n = len(l)
    x = l[0]
    for i in range(1,n):
        l[i-1] = l[i]
    l[n-1] = x
    
l = [10,20,30,40]
rotateByOne(l)
print(l)

[20, 30, 40, 10]


In [4]:
def rotateByD(l, d):
    n = len(l)              # Step 1: Get the length of the list (n = 4)
    d = d % n               # Step 2: Handle case when d > n. (e.g., d=6 → d=2)

    temp = l[:d]            # Step 3: Store the first d elements (temp = [10, 20])

    for i in range(d, n):   # Step 4: Shift remaining elements to the left
        l[i - d] = l[i]     # Move l[2] → l[0], l[3] → l[1]

    l[n - d:] = temp        # Step 5: Place the saved elements at the end
                           # l[2:] = [10, 20]

        
l = [10, 20, 30, 40, 50]
d = 2

rotateByD(l, d)
print("Rotated List:", l)

Rotated List: [30, 40, 50, 10, 20]


### Matrix QA

In [2]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


#### Reverse only columns (flip horizontally)

In [3]:
reversed_matrix = [row[::-1] for row in matrix]

print("[")
for row in reversed_matrix:
    print(" ", row)
print("]")

[
  [3, 2, 1]
  [6, 5, 4]
  [9, 8, 7]
]


#### Reverse only rows (flip vertically)

In [4]:
reversed_matrix =  matrix[::-1]

print("[")
for row in reversed_matrix:
    print(" ", row)
print("]")

[
  [7, 8, 9]
  [4, 5, 6]
  [1, 2, 3]
]


#### Reverse Colums and Rows both

In [6]:
import numpy as np
reversed_matrix = [row[::-1] for row in matrix[::-1]]
print(np.array(reversed_matrix))

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [7]:
import numpy as np 


reversed_matrix = np.flip(matrix)
print(reversed_matrix)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


## Leet code

In [5]:
class Solution(object):
    def twoSum(self, nums, target):
        # Dictionary to store the index of the numbers seen so far
        num_to_index = {}
        
        for i, num in enumerate(nums):
            # Calculate the complement needed to reach the target
            complement = target - num
            
            # Check if the complement exists in the dictionary
            if complement in num_to_index:
                return [num_to_index[complement], i]
            
            # Store the current number with its index
            num_to_index[num] = i

            
            
nums = [3, 2, 3]
target = 6
solution = Solution()
print(solution.twoSum(nums, target))  # Output: [0, 2]


[0, 2]


The for loop will iterate over the list using enumerate(), which provides both the index (i) and the value (num) of each element in nums.   
- i is the current index in the list.
- num is the current value at index i.

In [2]:
import random
import string

def generate_password(username, email, first_name, last_name):
    while True:
        # Define character pools
        special_chars = "!#$%&()*+,-./:;<=>?@[\\]_`{|}~"
        lower_case = string.ascii_lowercase
        upper_case = string.ascii_uppercase
        digits = string.digits
        
        # Ensure at least one character from each required category
        password = [
            random.choice(lower_case),
            random.choice(upper_case),
            random.choice(digits),
            random.choice(special_chars),
        ]
        
        # Fill the rest of the password to meet the length requirement
        all_chars = lower_case + upper_case + digits + special_chars
        password += random.choices(all_chars, k=random.randint(3, 8))  # Ensures total length between 7 and 12
        
        # Shuffle the password to avoid predictable patterns
        random.shuffle(password)
        password = ''.join(password)
        
        # Validate rules
        if (7 <= len(password) <= 12 and
            any(c.islower() for c in password) and
            any(c.isupper() for c in password) and
            any(c.isdigit() for c in password) and
            any(c in special_chars for c in password) and
            not any(password[i] == password[i+1] == password[i+2] for i in range(len(password) - 2)) and
            username.lower() not in password.lower() and
            email.lower() not in password.lower() and
            first_name.lower() not in password.lower() and
            last_name.lower() not in password.lower()):
            return password

# Example Usage
username = "Sadik"
email = "sadikashrafi@example.com"
first_name = "Sadik"
last_name = "Ashrafi"

valid_password = generate_password(username, email, first_name, last_name)
print("Generated Password:", valid_password)


Generated Password: -4Ulb[J\I;V(
